services:
  - type: web
    name: tectode-erp-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm --prefix backend install
    startCommand: npm --prefix backend start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: /api/v1
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: "Tec[ode ERP <onboarding@resend.dev>"
      - key: CORS_ORIGINS
        value: "*"
