import React from 'react';
import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Banknote,
  Building2,
  ChartColumn,
  Check,
  Circle,
  CircleDollarSign,
  CircleHelp,
  ClipboardList,
  ContactRound,
  CreditCard,
  Eye,
  EyeOff,
  Factory,
  FileText,
  FolderOpen,
  LayoutDashboard,
  MapPin,
  Menu,
  Package,
  PackageOpen,
  Receipt,
  RefreshCw,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Tags,
  Target,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Users,
  UsersRound,
  Wallet,
  Warehouse,
  X,
} from 'lucide-react-native';
import { COLORS } from '../tokens';

const ICONS = {
  dashboard: LayoutDashboard,
  finanzas: Wallet,
  inventario: Package,
  ventas: ShoppingCart,
  compras: ClipboardList,
  rrhh: UsersRound,
  analitica: ChartColumn,
  configuracion: Settings,
  usuarios: Users,
  empresa: Building2,
  clientes: ContactRound,
  proveedores: Truck,
  productos: Tags,
  alerta: TriangleAlert,
  buscar: Search,
  cerrar: X,
  check: Check,
  ver: Eye,
  ocultar: EyeOff,
  refrescar: RefreshCw,
  subir: ArrowUp,
  bajar: ArrowDown,
  flechaDerecha: ArrowRight,
  flechaIzquierda: ArrowLeft,
  menu: Menu,
  documento: FileText,
  ubicacion: MapPin,
  objetivo: Target,
  escudo: Shield,
  dinero: CircleDollarSign,
  tarjeta: CreditCard,
  gastos: Banknote,
  graficaBarras: ChartColumn,
  tendenciaArriba: TrendingUp,
  tendenciaAbajo: TrendingDown,
  carpetaVacia: FolderOpen,
  ayuda: CircleHelp,
  intercambio: ArrowLeftRight,
  fabrica: Factory,
  almacen: Warehouse,
  ordenes: PackageOpen,
  equipo: Users,
  cliente: ContactRound,
  proveedoresEtiquetas: Tags,
  recibo: Receipt,
};

export function TTIcon({
  name,
  size = 20,
  color = COLORS.textPrimary,
  strokeWidth = 1.75,
  ...props
}) {
  const Icon = ICONS[name];
  if (!Icon && __DEV__) console.warn(`TTIcon: nombre de ícono desconocido "${name}".`);

  const Component = Icon || Circle;
  return <Component size={size} color={color} strokeWidth={strokeWidth} {...props} />;
}